name: Build LSFG-Android

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          ndk-version: 25.2.9519653

      - name: Grant execute permission
        run: chmod +x LSFG-Android-Application/gradlew

      - name: Build APK
        working-directory: LSFG-Android-Application
        run: ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: LSFG-Android-APK
          path: LSFG-Android-Application/app/build/outputs/apk/debug/*.apk
